apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wgfff9gt7-go 
  janus-idp.io/tekton: wgfff9gt7-go
  backstage.io/kubernetes-id: wgfff9gt7-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgfff9gt7-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml